homePage: home
redirects:
  download-and-install:
    newPage: getting-started
    code: 301
  install:
    newPage: getting-started
    code: 301
  docs/hooks:
    newPage: advanced-development/hooks
    code: 301
  some-old-page:
    newPage: some-new-page
    code: 301
router:
tableOfContents:
  - page: home
    icon: fas fa-home
    children:
      - page: about
        # children:
        #   - page: benefits
      - page: join-us
      #   children:
      #     - page: contribute
      #       icon: fas fa-terminal
      #     - page: partnership
      #       icon: fas fa-handshake-angle
      #     - page: licenses
      #       icon: fas fa-stamp
  - page: getting-started
    icon: fas fa-download
    prev: features
    next: create-first-app
    children:
      - page: installation
      - page: nginx
  - page: cli-agent
    icon: fas fa-terminal
    children:
      - page: cli/init
  - page: apps
    icon: fas fa-bolt
    children:
      - page: apps/community
      - page: apps/enterprise
      - page: apps/external
  - page: docs
    icon: fas fa-book
    children:
      - page: docs/framework
        children:
          - page: docs/framework/routing
            children:
              - page: docs/framework/routing/defining-routes
              - page: docs/framework/routing/accessing-query-parameters
              - page: docs/framework/routing/parametric-routes
          - page: docs/framework/models
            children:
              - page: docs/framework/models/record-manager
              - page: docs/framework/models/records-api
              - page: docs/framework/models/description-api
              - page: docs/framework/models/enums-and-lookups
              - page: docs/framework/models/relations
              - page: docs/framework/models/callbacks
          - page: docs/framework/views
            children:
              - page: docs/framework/views/react-ui
          - page: docs/framework/controllers
            children:
              - page: docs/framework/controllers/html-output
              - page: docs/framework/controllers/json-output
          - page: docs/framework/ui
            children:
              - page: docs/framework/ui/creating-custom-components
              - page: docs/framework/ui/tables
              - page: docs/framework/ui/forms
              - page: docs/framework/ui/inputs
          - page: docs/framework/testing
            children:
              - page: docs/framework/testing/writing-tests
              - page: docs/framework/testing/running-tests
      - page: docs/erp
        children:
          - page: docs/erp/apps
            children:
              - page: docs/erp/apps/how-to-create-app
              - page: docs/erp/apps/folder-structure
              - page: docs/erp/apps/types
              - page: docs/erp/apps/manifest
              - page: docs/erp/apps/loader
          - page: docs/erp/conventions
          - page: docs/erp/localization
      - page: advanced-development
        icon: fas fa-medal
        children:
          - page: advanced-development/core-architecture
            children:
              - page: advanced-development/core-architecture/user-management-and-authentication
          - page: advanced-development/dynamic-routes
          - page: advanced-development/data-management
            children:
              - page: advanced-development/data-management/adding-custom-columns
              - page: advanced-development/data-management/create-own-data-grid-table-component
          - page: advanced-development/customizing-ui
            children:
              - page: advanced-development/customizing-ui/customizing-sidebar
              - page: advanced-development/customizing-ui/view
              - page: advanced-development/customizing-ui/component
              - page: advanced-development/customizing-ui/forms
              - page: advanced-development/customizing-ui/special-inputs
              - page: advanced-development/customizing-ui/skin
              - page: advanced-development/customizing-ui/material-ui
          - page: advanced-development/description-api
            children:
              - page: advanced-development/description-api/table
              - page: advanced-development/description-api/form
          - page: advanced-development/core-classes
            icon: fas fa-code
            children:
              - page: advanced-development/core-classes/loader
              - page: advanced-development/core-classes/model
              - page: advanced-development/core-classes/eloquent
              - page: advanced-development/core-classes/controller
              - page: advanced-development/core-classes/router
              - page: advanced-development/core-classes/permissions
          - page: advanced-development/design-patterns
            children:
            - page: advanced-development/crons
            - page: advanced-development/hooks
              children:
                - page: advanced-development/hooks/introduction
                - page: advanced-development/hooks/events
            - page: advanced-development/pipeline
            - page: advanced-development/miscellaneous/dashboard
          - page: advanced-development/miscellaneous
            children:
              - page: advanced-development/miscellaneous/hubleto-chatgpt
  - page: source-code
    icon: fa-solid fa-code
    children:
      - page: source-code/framework/Home
      - page: source-code/erp/Home
      - page: source-code/apps
        children:
          - page: source-code/apps/Calendar/Home
          - page: source-code/apps/Campaigns/Home
          - page: source-code/apps/Contacts/Home
          - page: source-code/apps/Customers/Home
          - page: source-code/apps/Deals/Home
          - page: source-code/apps/Invoices/Home
          - page: source-code/apps/Leads/Home
          - page: source-code/apps/Orders/Home
          - page: source-code/apps/Pipeline/Home
          - page: source-code/apps/Projects/Home
          - page: source-code/apps/Settings/Home
          - page: source-code/apps/Worksheets/Home
  - page: tutorials
    icon: fa-solid fa-graduation-cap
    children:
      - page: tutorials/using-ai-to-hubleto-vibe-code
        icon: fas fa-star
        children:
      - page: tutorials/hello-world-app
        icon: fas fa-star
        children:
          - page: basics/about-apps
          - page: basics/app-folder-structure
          - page: tutorial/add-route-controller-and-view
          - page: tutorial/create-simple-addressbook
            children:
            - page: tutorial/add-model-for-contacts
            - page: tutorial/add-route-controller-and-view-for-managing-contacts
            - page: tutorial/add-1-n-relation
          - page: tutorial/customize-tables-and-forms
          - page: tutorial/custom-ui-components
          - page: tutorial/writing-tests
          - page: tutorial/more-reading
      - page: tutorials/set-up-environment-for-development
        icon: fas fa-gears
      - page: tutorials/code-samples
  - page: certification
    icon: fas fa-id-badge
    children:
      - page: certification/level-1
        children:
          - page: certification/level-1/about-hubleto
          - page: certification/level-1/starting-the-development
          - page: certification/level-1/hubleto-core
          - page: certification/level-1/hubleto-apps
          - page: certification/level-1/recapitulation
      - page: certification/level-2
      - page: certification/level-3
      